/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author USUARIO
 */
public class VistaPrincipal extends javax.swing.JFrame {
    
    private Image imagenGato;
    private Image imagenBebedero;
    private boolean distancia = false;

    /**
     * Creates new form VistaPrincipal
     */
    public VistaPrincipal() {
        super("BEBEDERO SMARTCATS");
        initComponents();
        escalaImagenes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vistaPrincipal = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        gato = new javax.swing.JLabel();
        taza = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(java.awt.Color.white);

        vistaPrincipal.setBackground(new java.awt.Color(255, 255, 255));

        titulo.setFont(new java.awt.Font("Swis721 Lt BT", 1, 24)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("BEBEDERO");
        titulo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        gato.setBackground(new java.awt.Color(255, 255, 255));
        gato.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                gatoMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout vistaPrincipalLayout = new javax.swing.GroupLayout(vistaPrincipal);
        vistaPrincipal.setLayout(vistaPrincipalLayout);
        vistaPrincipalLayout.setHorizontalGroup(
            vistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaPrincipalLayout.createSequentialGroup()
                .addContainerGap(414, Short.MAX_VALUE)
                .addGroup(vistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vistaPrincipalLayout.createSequentialGroup()
                        .addComponent(titulo)
                        .addGap(362, 362, 362))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vistaPrincipalLayout.createSequentialGroup()
                        .addComponent(gato)
                        .addGap(67, 67, 67))))
            .addGroup(vistaPrincipalLayout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(taza)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        vistaPrincipalLayout.setVerticalGroup(
            vistaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vistaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo)
                .addGap(72, 72, 72)
                .addComponent(gato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 319, Short.MAX_VALUE)
                .addComponent(taza)
                .addGap(147, 147, 147))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(vistaPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void gatoMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gatoMouseDragged
        gato.setLocation( gato.getLocation().x + evt.getX() - gato.getWidth()/2, gato.getLocation().y + evt.getY() - gato.getHeight()/2);
        System.out.println(gato.getLocation().x);
        System.out.println(gato.getLocation().y);
        calcularDistacia(taza.getLocation().x, taza.getLocation().y, gato.getLocation().x, gato.getLocation().y);
        System.out.println(distancia);
    }//GEN-LAST:event_gatoMouseDragged

    public void escalaImagenes(){
        imagenGato = new ImageIcon(getClass().getResource("/images/Gato.PNG")).getImage();
        Image imagenGatoEscala = imagenGato.getScaledInstance(60, 60, Image.SCALE_SMOOTH);
        gato.setIcon(new ImageIcon(imagenGatoEscala));
        
        imagenBebedero = new ImageIcon(getClass().getResource("/images/Bebedero1.PNG")).getImage();
        Image imagenBebederoEscala = imagenBebedero.getScaledInstance(100, 200, Image.SCALE_SMOOTH);
        taza.setIcon(new ImageIcon(imagenBebederoEscala));
    }
    
    public boolean calcularDistacia(Integer x1, Integer y1, Integer x2, Integer y2) {
        
        Integer posicionX1 = x1 + 100;
        Integer posicionX2 = posicionX1 + 80;
        Integer posicionY1 = y1 + 120;
        Integer posicionY2 = y1 + 200;
        
        if (posicionX1 <= x2 && posicionX2 >= (x2+60) && posicionY1 <= y2 && posicionY2 >= (y2+60)){
            distancia = true;
        } else {
            distancia = false;
        }
        
        return distancia;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gato;
    private javax.swing.JLabel taza;
    private javax.swing.JLabel titulo;
    private javax.swing.JPanel vistaPrincipal;
    // End of variables declaration//GEN-END:variables
}
