/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smartcats;

import com.smartcats.logic.SocketClient;
import com.smartcats.view.Controller;
import com.smartcats.view.FeederModel;
import com.smartcats.view.View;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        SocketClient conexion = SocketClient.serverConnection();
        conexion.sendMessage("Hola serverSamrtCats!");
        
        System.out.println(new App().getGreeting());
        FeederModel feederModel = new FeederModel();
        Controller c = new Controller(feederModel);
        feederModel.setController(c);
        new View(c).setVisible(true);
        feederModel.taskFillDish();
    }
}
