/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.smart.cats.server;

import com.smart.cats.server.view.Controller;
import com.smart.cats.server.view.Model;
import com.smart.cats.server.view.View;

public class App {

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        Model m = new Model();
        Controller c = new Controller(m);
        m.setController(c);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View(c).setVisible(true);
            }
        });

    }
}
